# Generated by Django 4.2.13 on 2024-05-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='box',
            field=models.CharField(blank=True, choices=[('1', 'Oldest'), ('2', 'Youngest'), ('N', 'No')], max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='dances',
            field=models.CharField(blank=True, choices=[('1', 'Oldest'), ('2', 'Youngest'), ('N', 'No')], max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='fitness',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='football',
            field=models.CharField(blank=True, choices=[('1', 'Oldest'), ('2', 'Middle'), ('3', 'Youngest'), ('N', 'No')], max_length=1),
        ),
    ]
